# Development overrides for docker-compose.yml
version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stock_scanner
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: stock_scanner

  pgadmin:
    ports:
      - "5050:80"